# conda env create --file environment.yml
name: env_migration_sahel_africa
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=>=3.10
  - pip:
    - pyhere
    